Actualizacion 2 de junio 2025

diff --git a/bin/encode-to-utf-8 b/bin/encode-to-utf-8
--- a/bin/encode-to-utf-8
+++ b/bin/encode-to-utf-8
@@ -8,19 +8,21 @@ NC="\033[0m"
 DIRECTORY="./"
 ENCODING_OUT="UTF-8"
 
-find "$DIRECTORY" -type f -iname "*.es.srt" | while read archivo; do
-    ENCODING_IN=$(file -i "$archivo" | sed -n 's/.*charset=\([^;]*\)/\1/p')
-    NAME=$(basename "$archivo")
+# Inicio del script
+[ ! -f "$1" ] && printf "${RED}${BOLD}Se necesita el nombre del archivo de subtitulos${NC}\n" && exit
 
-    if [ "$ENCODING_IN" = "iso-8859-1" ]; then
-        printf "Convirtiendo $NAME (de $ENCODING_IN a $ENCODING_OUT)...\n"
-        iconv -f "$ENCODING_IN" -t "$ENCODING_OUT" "$archivo" > "$archivo.temp" && mv "$archivo.temp" "$archivo"
-        
-        # Verificar si la conversión fue exitosa
-        if [ $? -eq 0 ]; then
-            printf "${GREEN}${BOLD}¡Conversión exitosa!${NC}\n"
-        else
-            printf "${RED}${BOLD}Error al convertir el archivo $NAME${NC}\n"
-        fi
+ENCODING_IN=$(file -i "$1" | sed -n 's/.*charset=\([^;]*\)/\1/p')
+
+if [ "$ENCODING_IN" = "iso-8859-1" ]; then
+    printf "Convirtiendo $1 (de $ENCODING_IN a $ENCODING_OUT)...\n"
+    iconv -f "$ENCODING_IN" -t "$ENCODING_OUT" "$1" > "$1.temp" && mv "$1.temp" "$1"
+
+    # Verificar si la conversión fue exitosa
+    if [ $? -eq 0 ]; then
+        printf "${GREEN}${BOLD}¡Conversión exitosa!${NC}\n"
+    else
+        printf "${RED}${BOLD}Error al convertir el archivo $NAME${NC}\n"
     fi
-done
+else
+    printf "El archivo ya esta codificado en UTF-8\n"
+fi
